### ISSUE TITLE
The repository name (setting `repo_name`) cannot contain a hyphen

### ISSUE THREAD

**Issue by ewen-lbh** [aogier/chachacha#25]
So I tried to configure my chachacha for my repo and got the following:

```python
$ chachacha config repo_name ewen-lbh/pyrelease
Traceback (most recent call last):
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/bin/chachacha", line 11, in <module>
    sys.exit(main())
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/main.py", line 65, in added
    driver.add_entry("added", changes)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/drivers/kac.py", line 129, in add_entry
    self.write(current=current)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/drivers/kac.py", line 89, in write
    config = self.get_config(init=True)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/drivers/kac.py", line 169, in get_config
    return Configuration.factory(line)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/configuration.py", line 58, in factory
    configuration[Configuration.conf_map[arg[0]]] = arg[1:]
KeyError: 'l'
```

I hunted down the culprit and saw that you split configuration arguments on hyphens. As both GitHub and Gitlab allow hyphens in usernames and repository names, this will prevent projects and even _entire users_ (like me) to use your project, which is a bummer considering how great of a program this is :D

I propose using `:` instead, which is [not allowed in github usernames](https://user-images.githubusercontent.com/39094199/86517503-aa667780-be29-11ea-8336-d5f7a8d2b3a0.png) and [gitlab usernames](https://user-images.githubusercontent.com/39094199/86403626-61d67f00-bcae-11ea-9f4e-0e0f39b597c1.png)

**Comment by aogier** [comment]
Dear @ewen-lbh, I'm sorry for the delay, some corona stuff took me away from there but yeah, now I'm in! At a first glance your merge request seems very extensive and valid to me, please give me a bit of time as I'm still working and I'll definitely work on it, also, could you be interested in co-mantaining that? I like keep-a-changelog initiative and I think we definitely should have a supporting tool, I'd be glad to collaborate with other interested people :) 

see you later and thanks!

**Comment by aogier** [comment]
Hello! I've just merged your patch, thank your for your interest and contribution, and even patience, much appreciated, have a nice day!
